### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by 8Keep** [tlf30/iso-terrain-pbr#1]
Hi Trevor,
I'm trying to build this demo by running
```
./gradlew build
./gradlew run
```
The jme launcher starts, but when I get to the actual game, I get the jme error popup with this:
```
Uncaught exception thrown in Thread[jME3 Main,5,main]
RendererException: Shader failed to link, shader:Shader[numSources=2, numUniforms=29, numBufferBlocks=0, shaderSources=[ShaderSource[name=Shaders/ArrayPBRLighting.frag, defines, type=Fragment, language=GLSL150], ShaderSource[name=Shaders/ArrayPBRLighting.vert, defines, type=Vertex, language=GLSL150]]]
error: fragment shader input `vid' has no matching output in the previous stage
```
Here is the console output:
```
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :run
Apr 28, 2020 6:54:46 PM com.jme3.system.JmeDesktopSystem initialize
INFO: Running on jMonkeyEngine 3.3.2-stable
 * Branch: HEAD
 * Git Hash: 1a05e3f
 * Build Date: 2020-04-27
Apr 28, 2020 6:54:47 PM com.jme3.system.lwjgl.LwjglContext printContextInitInfo
INFO: LWJGL 2.9.3 context running on thread jME3 Main
 * Graphics Adapter: null
 * Driver Version: null
 * Scaling Factor: 1
Apr 28, 2020 6:54:47 PM com.jme3.renderer.opengl.GLRenderer loadCapabilitiesCommon
INFO: OpenGL Renderer Information
 * Vendor: X.Org
 * Renderer: AMD Radeon RX 5700 XT (NAVI10, DRM 3.36.0, 5.6.7-1-MANJARO, LLVM 10.0.0)
 * OpenGL Version: 4.6 (Compatibility Profile) Mesa 20.0.5
 * GLSL Version: 4.60
 * Profile: Compatibility
Apr 28, 2020 6:54:47 PM com.jme3.asset.AssetConfig loadText
WARNING: Cannot find loader com.jme3.scene.plugins.blender.BlenderModelLoader
Apr 28, 2020 6:54:47 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio Renderer Information
 * Device: OpenAL Soft
 * Vendor: OpenAL Community
 * Renderer: OpenAL Soft
 * Version: 1.1 ALSOFT 1.15.1
 * Supported channels: 64
 * ALC extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_loopback
 * AL extensions: AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFTX_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_source_latency
Apr 28, 2020 6:54:47 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
WARNING: Pausing audio device not supported.
Apr 28, 2020 6:54:47 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio effect extension version: 1.0
Apr 28, 2020 6:54:47 PM com.jme3.audio.openal.ALAudioRenderer initOpenAL
INFO: Audio max auxiliary sends: 4
28 Apr 2020 18:54:47 [ INFO | GuiGlobals ] Initializing GuiGlobals with:com.simsilica.lemur.GuiGlobals@7e842e1e
28 Apr 2020 18:54:47 [ INFO | GuiGlobals ] Lemur build date:20190427
28 Apr 2020 18:54:47 [ INFO | BaseStyles ] loadStyleResource(com/simsilica/lemur/style/base/glass-styles.groovy)
28 Apr 2020 18:54:47 [ INFO | BaseStyles ] Loading base resource:jar:file:/home/davisro/.gradle/caches/modules-2/files-2.1/com.simsilica/lemur-proto/1.9.1/6b36149a2ddcd08ea4cc25c9b673e3bf7c390133/lemur-proto-1.9.1.jar!/com/simsilica/lemur/style/base/glass-styles.groovy
28 Apr 2020 18:54:47 [ INFO | BaseStyles ] Loading extension resources for:com/simsilica/lemur/style/base/glass-styles.groovy
28 Apr 2020 18:54:47 [ INFO | BaseStyles ] Loading extension resource:jar:file:/home/davisro/.gradle/caches/modules-2/files-2.1/com.simsilica/lemur-props/1.0.1/5a8288f636e811d126e5c5524a22de36b60b955c/lemur-props-1.0.1.jar!/com/simsilica/lemur/style/base/glass-styles.groovy
28 Apr 2020 18:54:47 [ INFO | BaseStyles ] Loading extension resource:jar:file:/home/davisro/.gradle/caches/modules-2/files-2.1/com.simsilica/lemur/1.13.0/d13317df353f123d1c123797788107d00f7a9270/lemur-1.13.0.jar!/com/simsilica/lemur/style/base/glass-styles.groovy
Apr 28, 2020 6:54:48 PM com.jme3.material.Material checkSetParam
WARNING: Material parameter being set: Texture with type Texture2D doesn't match definition types TextureCubeMap
Apr 28, 2020 6:54:48 PM com.jme3.material.Material checkTextureParamColorSpace
WARNING: The texture Textures/test/Path.hdr has linear color space, but the material parameter Texture specifies no color space requirement, this may lead to unexpected behavior.
Check if the image was not set to another material parameter with a linear color space, or that you did not set the ColorSpace to Linear using texture.getImage.setColorSpace().
Apr 28, 2020 6:54:49 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: Shader failed to link, shader:Shader[numSources=2, numUniforms=29, numBufferBlocks=0, shaderSources=[ShaderSource[name=Shaders/ArrayPBRLighting.frag, defines, type=Fragment, language=GLSL150], ShaderSource[name=Shaders/ArrayPBRLighting.vert, defines, type=Vertex, language=GLSL150]]]
error: fragment shader input `vid' has no matching output in the previous stage

        at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1564)
        at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1576)
        at com.jme3.material.logic.SinglePassAndImageBasedLightingLogic.render(SinglePassAndImageBasedLightingLogic.java:259)
        at com.jme3.material.Technique.render(Technique.java:166)
        at com.jme3.material.Material.render(Material.java:1026)
        at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:614)
        at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
        at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
        at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:877)
        at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:779)
        at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1108)
        at com.jme3.renderer.RenderManager.render(RenderManager.java:1158)
        at com.jme3.app.SimpleApplication.update(SimpleApplication.java:272)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:153)
        at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:193)
        at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:234)
        at java.lang.Thread.run(Thread.java:748)
```

It looks like a shader file is not able to link correctly because of mismatched names.

**Comment by tlf30** [comment]
Ah, I honestly forgot about this repo. I have an updated set of shaders and fixes. I'll push them this evening when I get home.

**Comment by tlf30** [comment]
Sorry for the delay on this. I have seemingly broken how texcoord8 moves data into the shader. I am looking into why it has stopped working. (unrelated to your error, which was caused by an out-dated copy of the shader)

**Comment by tlf30** [comment]
@8Keep I figured out what I broke in the shader!
Give it a try now and let me know if it works for you. 

The shader is not perfect, but I lack even basic shader skills to understand all the problems that it has. It took months just to port the existing jme shader to work for this project. 

If you have any luck on improving it, I would love to know.

**Comment by 8Keep** [comment]
Now I get a weird error:

`Process 'command '/usr/lib/jvm/java-13-openjdk/bin/java'' finished with non-zero exit value 127`

I think this might have to do with jme with lwjgl2 on linux with a newer jdk, because I've gotten similar jdk failures before while using lwjgl2 on my machine.

When I switch out the dependency for lwjgl3, it does run fine, but the terrain material is all black. I don't remember what I was trying to do with this before but I don't remember it being all black.

**Comment by tlf30** [comment]
Hmm. I use openjdk 11 on windows when working on this project. Are you running it directly or using it as a library? I recommend attempting to run it directly without changing any of the render settings from the project and see if that works. 

During the initial load the terrain will look dark/black while the pbr light probe loads. It should finish loading after 10 seconds or so. 

EDIT: To run just use the `.\gradlew.bat run`
I just tried it on a clean clone of the repo on windows with openjdk11, and pbr shaders loaded in 10 to 15 seconds.

**Comment by 8Keep** [comment]
I did give it a few minutes and nothing changed from the black. I use gradle to build and run. I'll investigate a little more later.
